### ISSUE TITLE
proxmox-csi problem

### ISSUE THREAD

**Issue by speedkup** [LeoShivas/GitOps#3]
The installation of proxmox-csi unfortunately did not succeed; I would like to ask for your assistance. I will describe how I installed it:

1, I installed a new k8s cluster with 3 master node and 3 worker node.

2, Proxmox technical user create

```bash
pveum role add CSI -privs "VM.Audit VM.Config.Disk Datastore.Allocate Datastore.AllocateSpace Datastore.Audit"
pveum user add kubernetes-csi@pve
pveum user token add kubernetes-csi@pve csi -privsep 1
pveum aclmod / -user kubernetes-csi@pve -role CSI
pveum aclmod / -tokens 'kubernetes-csi@pve!csi' -role CSI
```

```bash
pveum role add CCM -privs "VM.Audit"
pveum user add kubernetes@pve
pveum user token add kubernetes@pve ccm -privsep 1
pveum aclmod / -user kubernetes@pve -role CCM
pveum aclmod / -tokens 'kubernetes@pve!ccm' -role CCM
```
3, Add node labels 
```bash
kubectl label nodes --all topology.kubernetes.io/region=pve --overwrite
kubectl label nodes --all topology.kubernetes.io/zone=pve --overwrite
```

4, Afterwards, I executed the following Ansible playbooks:

Prepare Kubernetes to Proxmox CSI playbook on all nodes:

```yaml
  tasks:
    - name: Add node IP in kubelet config
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: '^KUBELET_EXTRA_ARGS='
        line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }} --cloud-provider=external"
        state: present
        create: true
        mode: a+r

    - name: Systemctl raemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Kubectl Systemctl restart
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        enabled: true

    - name: Patch coredns tolerations
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        name: coredns
        namespace: kube-system
        definition:
          spec:
            template:
              spec:
                tolerations:
                  - key: node.cloudprovider.kubernetes.io/uninitialized
                    effect: NoSchedule
                    operator: Exists
      when: inventory_hostname in ['k8s-mn1']
      ```
5,  Deploy namespace, CMM and CSI

```yaml
  vars:
    proxmox_url: https://192.168.1.199:8006/api2/json
    state: present

  tasks:
  - name: Create Proxmox CSI namespace
    kubernetes.core.k8s:
      state: "{{ state }}"
      definition:
        api_version: v1
        kind: Namespace
        metadata:
          name: csi-proxmox
          labels:
            pod-security.kubernetes.io/enforce: privileged
#            pod-security.kubernetes.io/audit: baseline
#            pod-security.kubernetes.io/warn: baseline
            app.kubernetes.io/managed-by: Helm
          annotations:
            meta.helm.sh/release-name: proxmox-csi-plugin
            meta.helm.sh/release-namespace: csi-proxmox


  - name: Install Proxmox CCM chart
    kubernetes.core.helm:
      name: proxmox-cloud-controller-manager
      namespace: csi-proxmox
      chart_ref: oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager
      state: "{{ state }}"
      values:
        config:
          clusters:
            - url: "{{ proxmox_url }}"
              insecure: true
              token_id: "kubernetes@pve!ccm"
              token_secret: "secret"
              region: pve
        enabledControllers:
          - cloud-node
          - cloud-node-lifecycle
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""

  - name: Install Proxmox CSI chart
    kubernetes.core.helm:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
      chart_ref: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
      state: "{{ state }}"
      values:
        config:
          clusters:
            - url: "{{ proxmox_url }}"
              insecure: true
              token_id: "kubernetes-csi@pve!csi" # !
              token_secret: "secret"
              region: pve
        node:
          nodeSelector:
#            node.cloudprovider.kubernetes.io/platform: nocloud
          tolerations:
            - operator: Exists
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        storageClass:
          - name: proxmox-data
            storage: K8S
            reclaimPolicy: Delete
            fstype: ext4
            cache: none
```

```bash
root@k8s-mn1:~# kubectl get CSIDriver
NAME                       ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
csi.proxmox.sinextra.dev   true             true             true              <unset>         false               Persistent   46m
```
```bash
root@k8s-mn1:~# kubectl get csistoragecapacities -ocustom-columns=CLASS:.storageClassName,AVAIL:.capacity,ZONE:.nodeTopology.matchLabels -A
CLASS          AVAIL         ZONE
proxmox-data   108915184Ki   map[topology.kubernetes.io/region:pve topology.kubernetes.io/zone:pve]
```
```bash
root@k8s-mn1:/home/master# kubectl get nodes --show-labels
NAME                  STATUS   ROLES           AGE   VERSION    LABELS
k8s-mn1.proxmox.lan   Ready    control-plane   8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-mn1.proxmox.lan,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
k8s-mn2.proxmox.lan   Ready    control-plane   8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-mn2.proxmox.lan,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
k8s-mn3.proxmox.lan   Ready    control-plane   8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-mn3.proxmox.lan,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
k8s-wn1.proxmox.lan   Ready    <none>          8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-wn1.proxmox.lan,kubernetes.io/os=linux,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
k8s-wn2.proxmox.lan   Ready    <none>          8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-wn2.proxmox.lan,kubernetes.io/os=linux,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
k8s-wn3.proxmox.lan   Ready    <none>          8h    v1.25.14   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-wn3.proxmox.lan,kubernetes.io/os=linux,topology.kubernetes.io/region=pve,topology.kubernetes.io/zone=pve
```

```bash
root@k8s-mn1:/home/master# ps axfwww | grep cloud-provider=external
 152052 pts/1    S+     0:00                              \_ grep --color=auto cloud-provider=external
 144538 ?        Ssl    0:20 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --pod-infra-container-image=registry.k8s.io/pause:3.8 --node-ip=192.168.1.81 --cloud-provider=external
```
```bash
root@k8s-mn1:/home/master# kubectl describe node k8s-mn1
Name:               k8s-mn1.proxmox.lan
Roles:              control-plane
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k8s-mn1.proxmox.lan
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node.kubernetes.io/exclude-from-external-load-balancers=
                    topology.kubernetes.io/region=pve
                    topology.kubernetes.io/zone=pve
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.1.81
                    csi.volume.kubernetes.io/nodeid: {"csi.proxmox.sinextra.dev":"k8s-mn1.proxmox.lan"}
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"02:ee:f0:58:54:a3"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.1.81
                    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 31 Jan 2024 11:21:59 +0100
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  k8s-mn1.proxmox.lan
  AcquireTime:     <unset>
  RenewTime:       Wed, 31 Jan 2024 20:27:33 +0100
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 31 Jan 2024 11:26:16 +0100   Wed, 31 Jan 2024 11:26:16 +0100   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Wed, 31 Jan 2024 20:27:22 +0100   Wed, 31 Jan 2024 11:21:59 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Wed, 31 Jan 2024 20:27:22 +0100   Wed, 31 Jan 2024 11:21:59 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Wed, 31 Jan 2024 20:27:22 +0100   Wed, 31 Jan 2024 11:21:59 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Wed, 31 Jan 2024 20:27:22 +0100   Wed, 31 Jan 2024 20:02:53 +0100   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  192.168.1.81
  Hostname:    k8s-mn1.proxmox.lan
Capacity:
  cpu:                4
  ephemeral-storage:  16399228Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             4017636Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  15113528500
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3915236Ki
  pods:               110
System Info:
  Machine ID:                 f78d55719a6347d9a8051fed937becaf
  System UUID:                1ae828d8-1f5c-4963-9b62-f9025834515e
  Boot ID:                    481e0167-7fdd-4c56-b99a-a60006e84b9f
  Kernel Version:             5.15.0-73-generic
  OS Image:                   Ubuntu 22.04.2 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.24
  Kubelet Version:            v1.25.14
  Kube-Proxy Version:         v1.25.14
PodCIDR:                      10.244.0.0/24
PodCIDRs:                     10.244.0.0/24
Non-terminated Pods:          (8 in total)
  Namespace                   Name                                                 CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                 ------------  ----------  ---------------  -------------  ---
  csi-proxmox                 proxmox-cloud-controller-manager-5554b59bd8-z2ptm    10m (0%)      0 (0%)      32Mi (0%)        0 (0%)         21m
  csi-proxmox                 proxmox-csi-plugin-node-w42fv                        20m (0%)      0 (0%)      32Mi (0%)        0 (0%)         21m
  kube-flannel                kube-flannel-ds-gb72c                                100m (2%)     0 (0%)      50Mi (1%)        0 (0%)         9h
  kube-system                 etcd-k8s-mn1.proxmox.lan                             100m (2%)     0 (0%)      100Mi (2%)       0 (0%)         9h
  kube-system                 kube-apiserver-k8s-mn1.proxmox.lan                   250m (6%)     0 (0%)      0 (0%)           0 (0%)         9h
  kube-system                 kube-controller-manager-k8s-mn1.proxmox.lan          200m (5%)     0 (0%)      0 (0%)           0 (0%)         9h
  kube-system                 kube-proxy-5d74b                                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         9h
  kube-system                 kube-scheduler-k8s-mn1.proxmox.lan                   100m (2%)     0 (0%)      0 (0%)           0 (0%)         9h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                780m (19%)  0 (0%)
  memory             214Mi (5%)  0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type     Reason                   Age   From     Message
  ----     ------                   ----  ----     -------
  Normal   Starting                 24m   kubelet  Starting kubelet.
  Warning  InvalidDiskCapacity      24m   kubelet  invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  24m   kubelet  Node k8s-mn1.proxmox.lan status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    24m   kubelet  Node k8s-mn1.proxmox.lan status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     24m   kubelet  Node k8s-mn1.proxmox.lan status is now: NodeHasSufficientPID
  Normal   NodeNotReady             24m   kubelet  Node k8s-mn1.proxmox.lan status is now: NodeNotReady
  Normal   NodeAllocatableEnforced  24m   kubelet  Updated Node Allocatable limit across pods
  Normal   NodeReady                24m   kubelet  Node k8s-mn1.proxmox.lan status is now: NodeReady
```

kubectl logs -n csi-proxmox proxmox-cloud-controller-manager-5554b59bd8-z2ptm
```bash
E0131 20:01:22.377790       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-wn2.proxmox.lan: vm 'k8s-wn2.proxmox.lan' not found, skipped
E0131 20:01:22.386360       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-wn3.proxmox.lan: vm 'k8s-wn3.proxmox.lan' not found, skipped
E0131 20:01:22.394055       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-wn1.proxmox.lan: vm 'k8s-wn1.proxmox.lan' not found, skipped
E0131 20:01:22.401728       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-mn1.proxmox.lan: vm 'k8s-mn1.proxmox.lan' not found, skipped
E0131 20:01:22.410142       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-mn2.proxmox.lan: vm 'k8s-mn2.proxmox.lan' not found, skipped
E0131 20:01:22.417275       1 node_controller.go:281] Error getting instance metadata for node addresses: instances.InstanceMetadata() - failed to find instance by name k8s-mn3.proxmox.lan: vm 'k8s-mn3.proxmox.lan' not found, skipped
I0131 20:01:22.417313       1 node_controller.go:267] Update 6 nodes status took 51.5206ms.
```
Is there any idea about what I might have missed or done wrong?
